services:
  orders-api:
    restart: always
    image: node:20-alpine
    container_name: orders-api
    working_dir: /app
    volumes: ["./orders-api:/app"]
    command: ["sh","-lc","npm i && npm run dev -- --host 0.0.0.0 --port 8081"]
    ports: ["8081:8081"]
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=10.1.0.11:9092,10.1.0.12:9092,10.1.0.13:9092
      - ORDERS_TOPIC=orders.v1

  status-api:
    restart: always
    image: node:20-alpine
    container_name: status-api
    working_dir: /app
    volumes: ["./status-api:/app"]
    command: ["sh","-lc","npm i && npm run dev -- --host 0.0.0.0 --port 8082"]
    ports: ["8082:8082"]
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=10.1.0.11:9092,10.1.0.12:9092,10.1.0.13:9092
      - ORDERS_TOPIC=orders.v1
      - STATUS_TOPIC=order_status.v1
      - GROUP_ID=status-api-v1

  frontend:
    restart: always
    image: node:20-alpine
    container_name: frontend
    working_dir: /app
    volumes: ["./frontend:/app"]
    command: ["sh","-lc","npm i && npm run dev -- --host 0.0.0.0 --port 3000"]
    ports: ["3000:3000"]
    environment:
      - API_URL=http://localhost:8082
